### ISSUE TITLE
Assertion `ByteCode Updward Exposed Used Mismatch` failed

### ISSUE THREAD

**Issue by Changochen** [chakra-core/ChakraCore#6487]
Version: `ch version 1.12.0.0-beta`

Git hash: `33db8efd9f02cd528a7305391d7d10765a2e85f3`

POC that causes the assertion:
```javascript
function a() {
  class b extends Array {}
  a();
}
a()
```

POC that causes a segfault in release build:
```javascript
function a() {
  class b extends 'x'.match
  (Array) {}
  a()
}
a()
```

**Comment by Fly-Style** [comment]
Thank you for the report, I'll check it soon!

**Comment by ppenzin** [comment]
I can confirm both tests fail.

**Comment by rhuanjl** [comment]
Bug here is that the reg for the object after `extends` is missing its bytecodeuses marker. So when bailing out it is missing.

HOWEVER this appears to expose something else pathological - case 2 here gets jitted after running several times AND hits a BailOnNoProfile on the first run in the JIT triggering the segfault.

There is no way there should be a BailOnNoProfile being hit here unless a flag had been used to force early jitting (which it hasn't) - the branches in the code go the same way every time.

That said this is a bug with jitting class declarations - in most normal use cases a class declaration occurs only once and so is not jitted.

EDIT: the BailOnNoProfile is actually nothing to do with the class declaration; it's because the function has never completed execution - it's being recursively called without ever running to completion - this is a different issue; and may warrant other consideration/an adjustment to the logic of BailOnNoProfile - it seems we should either disable BailOnNoProfile in such cases OR disable jitting in such cases.

**Comment by rhuanjl** [comment]
I have a fix for the crash BUT it doesn't fix the pathological bailouts.

`class b extends null` OR `class b extends expr_returning_null` if jitted leads to a guaranteed bailout when executed both with and without my fix I'm going to think about ways to fix that too before submitting.
