### ISSUE TITLE
Assertion failure in ArrayBuffer::EntrySlice()

### ISSUE THREAD

**Issue by sunlili** [chakra-core/ChakraCore#6543]
Hello, executing following code in ch 1.11.24(debug), an assertion will be thrown.
```
function opt(buffer) {
    let obj = [2.3023e-320]; 
    var result = buffer.slice(obj.x, obj.x);
}
function main() {
    for (let i = 0; i < 1000; i++) {
        var buffer = new ArrayBuffer(8);
        opt(buffer);
    }   

    buffer = new ArrayBuffer(2147483647);
    opt(buffer);
}
main();     
```
output:
```
ASSERTION 26608: (c:\users\sunlili\documents\workspace\jsenginesfordebug\chakracore-1.11.24\lib\runtime\library\arraybuffer.cpp, line 569) newLen < MaxArrayBufferLength
 Failure: (newLen < MaxArrayBufferLength)
FATAL ERROR: ch.exe failed due to exception code c0000420
```
<img width="772" alt="tmp" src="https://user-images.githubusercontent.com/10752186/102328403-fe24e180-3fc1-11eb-831c-f125035e4544.png">

`newLen` is 0x7fffffff, which equals to MaxArrayBufferLength. I think the assertion should be 'newLen <= MaxArrayBufferLength'.

ISec Lab.
2020.12.16

**Comment by rhuanjl** [comment]
Thanks for the report, this is a bug in 1.11 BUT has already been fixed in the master branch with this commit: https://github.com/microsoft/ChakraCore/commit/ed3377c1cf489dc78410628ca2d81e5c434cd6e1#diff-5aaaad9cd76e7dd83dec4bbf6204562f0a811ec997bdb4f5cbdd1c08040bf3bf

We will not be updating the 1.11 branch.
