### ISSUE TITLE
Something wrong when downloading chakracore.

### ISSUE THREAD

**Issue by Redbeanw44602** [chakra-core/ChakraCore#6714]
When I try to download the latest release of ChakraCore:
![p](https://user-images.githubusercontent.com/29711228/116958605-c8ad3600-accd-11eb-9eec-0b4ef1a34460.png)

I tried to change the network environment, but I still get a domain name resolution error.
Please fix it, thanks.

Download Link: `https://aka.ms/chakracore/cc_windows_all_1_11_24`
TIME: 2021/05/04 UTC 3:45

**Comment by rhuanjl** [comment]
It looks like either there's an outage or Microsoft has deleted their hosted binaries.

Source code of the release can still be downloaded:
https://github.com/chakra-core/ChakraCore/archive/refs/tags/v1.11.24.zip
https://github.com/chakra-core/ChakraCore/archive/refs/tags/v1.11.24.tar.gz

@LouisLaf @pleath please could you tell us if this is intentional?

**Comment by Redbeanw44602** [comment]
Download resumed.

**Comment by LouisLaf** [comment]
This was a mistake on our part. Thanks for reporting, it should be fixed now.

-- Louis
