### ISSUE TITLE
Native Objects and External Data

### ISSUE THREAD

**Issue by bkimman** [chakra-core/ChakraCore#6871]
A key usage while embedding a scripting engine in an application is to create 'native' objects.

Two types of native objects are possible:
a) those which are created by the host and exposed to the script
b) those which can be created from the script with 'new' - here the host provides a constructor function.

Typically, these objects will be backed by some memory address storing data about the object. 

For (b) above, the object is created by the chakra core and so JsSetExternalData returns 'JsErrorInvalidArgument'. 

So for these type of objects, what would be the recommended way to store an address containing the data .. would it be to define a readonly property in the constructor?

Also, what should the return value be of the constructor .. should it be the new object as indicated by info->thisArg or arguments[0]?

Thanks
K

**Comment by rhuanjl** [comment]
@fatcerberus can you remember how you did this - I think I remember that it takes more than one API call, but not what the step by step is.

**Comment by fatcerberus** [comment]
@rhuanjl @bkimman

Thanks, I needed an excuse to dig into the neoSphere codebase again. 😄

1. For a) it's fairly simple: https://github.com/spheredev/neosphere/blob/main/src/shared/jsal.c#L1489-L1511

2. b) is a bit trickier but basically you want to do the same as a) and just directly return that object from the native constructor.  I say this is trickier only because you might need to set up the prototype chain appropriately, account for `new.target`, etc.--all the stuff JS normally does automatically when calling a constructor.  I actually have the additional logic for that here: https://github.com/spheredev/neosphere/blob/main/src/shared/api.c#L495-L502

**Comment by bkimman** [comment]
Thanks @fatcerberus  .. glad I gave you an excuse to dig into the code base again .. I just downloaded it to have a look .. some of the comments I read while browsing seemed really useful .. thanks again.
